### ISSUE TITLE
down

### ISSUE THREAD

**Issue by JavaPluginFX** [FreeGamingHere/Core#2]

**Comment by ByxNilsGFXx** [comment]
ITS Not your PluginTask

**Comment by ByxNilsGFXx** [comment]
You downloader

**Comment by treehousemc1** [comment]
Whos creator then?

**Comment by FreeGamingHere** [comment]
What do you mean? @JavaPluginFX ?

**Comment by JavaPluginFX** [comment]
Its a Download Plugin

**Comment by JavaPluginFX** [comment]
Its Not your Codes

**Comment by JavaPluginFX** [comment]
Its leaked

**Comment by FreeGamingHere** [comment]
Yep, it's mine. Keep spamming here I do not care. Use the issues to report a plugin bug, not how stupid you are.
